# Generated by Django 3.1.3 on 2021-03-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('condition', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('actionStamp', models.DateTimeField()),
                ('closeStamp', models.DateTimeField()),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVolunteer', models.BooleanField(default=False)),
                ('isDonor', models.BooleanField(default=False)),
                ('isAdopter', models.BooleanField(default=False)),
                ('donatedAmount', models.FloatField(default=0)),
                ('activities', models.ManyToManyField(to='app.Activity')),
                ('adoptedPets', models.ManyToManyField(to='app.PetProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
