# Generated by Django 3.1.3 on 2021-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210316_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timeStamp', '-actionStamp', '-closeStamp']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='reporter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer',
            field=models.CharField(default='mowli', max_length=255),
            preserve_default=False,
        ),
    ]
