# Generated by Django 3.1.3 on 2021-03-21 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210321_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dateofBirth',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 14, 49, 33, 157993, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='donorSince',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 14, 49, 39, 549276, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
