# Generated by Django 3.1.3 on 2021-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210321_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activities',
            field=models.ManyToManyField(blank=True, to='app.Activity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adoptedPets',
            field=models.ManyToManyField(blank=True, to='app.PetProfile'),
        ),
    ]
