# Generated by Django 3.1.3 on 2021-03-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_petprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='contact',
        ),
    ]
