# Generated by Django 3.1.3 on 2021-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210325_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
