# Generated by Django 3.1.3 on 2021-03-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_petprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
