# Generated by Django 3.1.3 on 2021-03-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='type',
        ),
    ]
