# Generated by Django 3.1.3 on 2021-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_timeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
