# Generated by Django 3.1.3 on 2021-03-29 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_petprofile_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
