# Generated by Django 3.1.3 on 2021-03-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_petprofile_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='adopted',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='time',
        ),
    ]
