# Generated by Django 3.1.3 on 2021-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210329_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
