# Generated by Django 3.1.5 on 2021-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
