# Generated by Django 3.1.5 on 2021-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210429_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='panCard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
