# Generated by Django 3.1.5 on 2021-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateofBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
